credentials = ""  # API credentials.
customer_id = ""  # Customer ID.
url = ""  # Website.
site = ""  # Tenant site.
cluster = ""  # Tenant cluster.
start_date = ""  # Start date.
end_date = ""  # End date.
pbx_id = ""  # PBX Id.
subscription_id = ""  # Subscription ID.
