credentials = ""  # API credentials.
customer_id = ""  # Customer ID.
url = ""  # Website.
site = ""  # Tenant site.
cluster = ""  # Tenant cluster.
start_date = ""  # Start date.
end_date = ""  # End date.
pbx_id = ""  # PBX Id.
subscription_id = ""  # Subscription ID.
user_first_name = ""  # User first name.
user_last_name = ""  # User last name.
